"""Report generator module — PDF and Markdown export."""

import pandas as pd
from datetime import datetime
from typing import Dict, List, Any, Optional
import io


def generate_markdown_report(
    overview: Dict[str, Any],
    col_types: Dict[str, List[str]],
    indicators: List[Dict[str, str]],
    correlations: List[Dict[str, Any]],
    insights: str,
    source_name: str,
) -> str:
    """Generate a comprehensive Markdown analysis report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        "# Public Health Data Insights Report",
        f"*Generated: {now}*",
        f"*Data Source: {source_name}*",
        "",
        "---",
        "",
        "## 1. Dataset Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Rows | {overview['rows']:,} |",
        f"| Columns | {overview['columns']} |",
        f"| Missing Values | {overview['total_missing']:,} |",
        f"| Duplicate Rows | {overview['duplicate_rows']} |",
        f"| Memory Usage | {overview['memory_mb']} MB |",
        "",
        "### Column Types",
        "",
        f"- **Numeric ({len(col_types.get('numeric', []))}):** {', '.join(col_types.get('numeric', [])) or 'None'}",
        f"- **Categorical ({len(col_types.get('categorical', []))}):** {', '.join(col_types.get('categorical', [])) or 'None'}",
        f"- **Date ({len(col_types.get('date', []))}):** {', '.join(col_types.get('date', [])) or 'None'}",
        "",
        "### Missing Values by Column",
        "",
    ]

    for col, missing in overview["missing_values"].items():
        if missing > 0:
            lines.append(f"- **{col}:** {missing}")

    if overview["total_missing"] == 0:
        lines.append("*No missing values detected.*")

    lines.extend(["", "---", "", "## 2. Public Health Indicators", ""])

    if indicators:
        lines.append("| Column | Type |")
        lines.append("|--------|------|")
        for ind in indicators:
            lines.append(f"| {ind['column']} | {ind['type']} |")
    else:
        lines.append("*No health indicators automatically identified.*")

    lines.extend(["", "---", "", "## 3. Correlations", ""])

    if correlations:
        lines.append("| Variable 1 | Variable 2 | Correlation | Strength |")
        lines.append("|-----------|-----------|-------------|----------|")
        for c in correlations:
            lines.append(f"| {c['var1']} | {c['var2']} | {c['correlation']} | {c['strength']} |")
    else:
        lines.append("*No strong correlations found.*")

    lines.extend(["", "---", "", "## 4. AI-Generated Insights", ""])
    lines.append(insights)
    lines.extend(["", "---", "", f"*Report generated by Public Health Data Insights Agent — {now}*"])

    return "\n".join(lines)


def generate_pdf_report_html(
    overview: Dict[str, Any],
    col_types: Dict[str, List[str]],
    indicators: List[Dict[str, str]],
    correlations: List[Dict[str, Any]],
    insights: str,
    source_name: str,
) -> str:
    """Generate an HTML document that can be converted to PDF via weasyprint or browser."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    md = generate_markdown_report(overview, col_types, indicators, correlations, insights, source_name)

    # Convert markdown basics to HTML (simple approach)
    html_body = md
    # Headers
    for i in range(1, 5):
        prefix = "#" * i
        import re
        html_body = re.sub(rf"^{prefix} (.+)$", rf"<h{i}>\1</h{i}>", html_body, flags=re.MULTILINE)
    # Bold
    html_body = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html_body)
    # Italic
    html_body = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html_body)
    # Horizontal rules
    html_body = html_body.replace("---", "<hr>")
    # Tables — just wrap in <pre> for simplicity in PDF
    html_body = re.sub(r"(\|.+\|[\n\r]+\|[-| :]+\|[\n\r]+((\|.+\|[\n\r]*)+))",
                       r"<pre>\1</pre>", html_body)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #1A1A2E; line-height: 1.6; }}
  h1 {{ color: #0D7377; border-bottom: 2px solid #0D7377; padding-bottom: 8px; }}
  h2 {{ color: #1A1A2E; margin-top: 30px; }}
  h3 {{ color: #0D7377; }}
  hr {{ border: none; border-top: 1px solid #ddd; margin: 30px 0; }}
  pre {{ background: #f5f7fa; padding: 12px; border-radius: 4px; font-size: 13px; overflow-x: auto; }}
  strong {{ color: #0D7377; }}
  table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
  th {{ background: #0D7377; color: white; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""